language: python
cache: pip
sudo: false

# Supported CPython versions:
# https://en.wikipedia.org/wiki/CPython#Version_history
matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
 - pip install -U pip
 - pip install -U black flake8

script:
 # Static analysis
 - flake8 --statistics --count
 - black --check --diff .
